class MimeMap:
    def __init__(self):
        pass

    mimes = {"xlt": "application/vnd.ms-excel", "css": "text/css", "fif": "application/fractals",
             "xlw": "application/vnd.ms-excel", "ps": "application/postscript", "pma": "application/x-perfmon",
             "pmc": "application/x-perfmon", "csv": "text/csv", "pml": "application/x-perfmon",
             "der": "application/x-x509-ca-cert", "exe": "application/octet-stream", "pmr": "application/x-perfmon",
             "bas": "text/plain", "scd": "application/x-msschedule", "sst": "application/vnd.ms-pkicertstore",
             "dvi": "application/x-dvi", "jar": "application/zip", "pmw": "application/x-perfmon",
             "wks": "application/vnd.ms-works", "ram": "audio/x-pn-realaudio", "qt": "video/quicktime",
             "cdf": "application/x-cdf", "ras": "image/x-cmu-raster", "sct": "text/scriptlet",
             "bcpio": "application/x-bcpio", "tex": "application/x-tex", "ai": "application/postscript",
             "png": "image/png",
             "stl": "application/vnd.ms-pkistl", "stm": "text/html", "texinfo": "application/x-texinfo",
             "pnm": "image/x-portable-anymap", "ra": "audio/x-pn-realaudio", "au": "audio/basic",
             "mht": "message/rfc822",
             "mid": "audio/mid", "xof": "x-world/x-vrml", "cer": "application/x-x509-ca-cert",
             "wmf": "application/x-msmetafile", "pot": "application/vnd.ms-powerpoint", "sh": "application/x-sh",
             "jpeg": "image/jpeg", "dxr": "application/x-director",
             "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "c": "text/plain",
             "lha": "application/octet-stream", "rtf": "application/rtf", "svg": "image/svg+xml",
             "tgz": "application/x-compressed", "h": "text/plain", "ppm": "image/x-portable-pixmap",
             "flr": "x-world/x-vrml", "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
             "txt": "text/plain", "pps": "application/vnd.ms-powerpoint", "t": "application/x-troff",
             "xpm": "image/x-xpixmap", "asf": "video/x-ms-asf", "ppt": "application/vnd.ms-powerpoint",
             "rtx": "text/richtext", "z": "application/x-compress", "cpio": "application/x-cpio",
             "tr": "application/x-troff", "asr": "video/x-ms-asf", "swf": "application/x-shockwave-flash",
             "asx": "video/x-ms-asf", "isp": "application/x-internet-signup", "dir": "application/x-director",
             "latex": "application/x-latex", "hqx": "application/mac-binhex40", "p10": "application/pkcs10",
             "p12": "application/x-pkcs12", "tif": "image/tiff", "ico": "image/x-icon",
             "acx": "application/internet-property-stream", "lzh": "application/octet-stream", "xaf": "x-world/x-vrml",
             "prf": "application/pics-rules",
             "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
             "pbm": "image/x-portable-bitmap", "wps": "application/vnd.ms-works", "uls": "text/iuls",
             "xbm": "image/x-xbitmap", "aiff": "audio/x-aiff", "eml": "message/rfc822", "aifc": "audio/x-aiff",
             "ief": "image/ief", "rgb": "image/x-rgb", "hta": "application/hta", "avi": "video/x-msvideo",
             "htc": "text/x-component", "sv4crc": "application/x-sv4crc", "json": "application/json",
             "class": "application/octet-stream", "sit": "application/x-stuffit", "htm": "text/html",
             "ustar": "application/x-ustar", "dll": "application/x-msdownload", "htt": "text/webviewhtml",
             "hdf": "application/x-hdf", "wav": "audio/x-wav", "mp2": "video/mpeg", "wri": "application/x-mswrite",
             "mp4": "video/mp4", "wrl": "x-world/x-vrml", "mp3": "audio/mpeg",
             "setreg": "application/set-registration-initiation", "gz": "application/x-gzip", "pdf": "application/pdf",
             "mny": "application/x-msmoney", "pub": "application/x-mspublisher", "wrz": "x-world/x-vrml",
             "movie": "video/x-sgi-movie", "setpay": "application/set-payment-initiation",
             "bin": "application/octet-stream", "dms": "application/octet-stream", "texi": "application/x-texinfo",
             "mov": "video/quicktime", "axs": "application/olescript", "mpa": "video/mpeg",
             "wcm": "application/vnd.ms-works", "zip": "application/zip", "mpe": "video/mpeg", "mpg": "video/mpeg",
             "clp": "application/x-msclip", "eps": "application/postscript", "mpp": "application/vnd.ms-project",
             "oda": "application/oda", "wdb": "application/vnd.ms-works", "doc": "application/msword",
             "aif": "audio/x-aiff", "pfx": "application/x-pkcs12", "xwd": "image/x-xwindowdump",
             "dot": "application/msword", "iii": "application/x-iphone", "js": "application/x-javascript",
             "m13": "application/x-msmediaview", "cmx": "image/x-cmx", "m14": "application/x-msmediaview",
             "pgm": "image/x-portable-graymap", "vcf": "text/x-vcard", "man": "application/x-troff-man",
             "jfif": "image/pipeg", "snd": "audio/basic", "mpv2": "video/mpeg", "vrml": "x-world/x-vrml",
             "shar": "application/x-shar", "cod": "image/cis-cod", "p7b": "application/x-pkcs7-certificates",
             "p7c": "application/x-pkcs7-mime", "msg": "application/vnd.ms-outlook", "bmp": "image/bmp",
             "p7m": "application/x-pkcs7-mime", "roff": "application/x-troff", "p7r": "application/x-pkcs7-certreqresp",
             "p7s": "application/x-pkcs7-signature", "rmi": "audio/mid", "me": "application/x-troff-me",
             "html": "text/html", "tar": "application/x-tar", "ms": "application/x-troff-ms",
             "spc": "application/x-pkcs7-certificates", "etx": "text/x-setext", "mhtml": "message/rfc822",
             "mdb": "application/x-msaccess", "spl": "application/futuresplash", "trm": "application/x-msterminal",
             "323": "text/h323", "nc": "application/x-netcdf", "mpeg": "video/mpeg", "lsf": "video/x-la-asf",
             "tiff": "image/tiff", "gif": "image/gif", "nws": "message/rfc822", "m3u": "audio/x-mpegurl",
             "lsx": "video/x-la-asf", "dcr": "application/x-director", "crd": "application/x-mscardfile",
             "pko": "application/ynd.ms-pkipko", "tsv": "text/tab-separated-values",
             "cat": "application/vnd.ms-pkiseccat",
             "sv4cpio": "application/x-sv4cpio", "mvb": "application/x-msmediaview", "crl": "application/pkix-crl",
             "tcl": "application/x-tcl", "jpe": "image/jpeg", "jpg": "image/jpeg", "crt": "application/x-x509-ca-cert",
             "src": "application/x-wais-source", "evy": "application/envoy", "xla": "application/vnd.ms-excel",
             "hlp": "application/winhlp", "gtar": "application/x-gtar", "xlc": "application/vnd.ms-excel",
             "ins": "application/x-internet-signup", "xlm": "application/vnd.ms-excel", "csh": "application/x-csh",
             "xls": "application/vnd.ms-excel"}

    simplemimes = {"xlt": "application/vnd.ms-excel", "css": "text/css",
                   "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                   "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                   "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                   "gz": "application/x-gzip", "pdf": "application/pdf", "tiff": "image/tiff", "gif": "image/gif",
                   "bin": "application/octet-stream", "mpeg": "video/mpeg", "ico": "image/x-icon",
                   "html": "text/html", "mov": "video/quicktime", "mp4": "video/mp4", "png": "image/png",
                   "doc": "application/msword"
                   }
